# ===========================================
# Pipeline CI para Selenium Screenplay Cucumber 2.0
# Versión estable 2025 sin tareas obsoletas
# ===========================================

trigger:
  branches:
    include:
      - main
      - develop
      - feature/*

pool:
  name: Default

variables:
  MAVEN_OPTS: "-Dmaven.test.failure.ignore=false"

steps:
  # 1️⃣ Checkout del código
  - checkout: self
    displayName: "Checkout del repositorio"

  # 2️⃣ Configurar Java 17 manualmente (más estable)
  - script: |
      echo "Instalando JDK 17..."
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      java -version
      echo "JAVA_HOME configurado:"
      echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/java-17-openjdk-amd64"
    displayName: "Instalar y configurar JDK 17"

  # 3️⃣ Compilar y ejecutar pruebas con Maven
  - script: |
      set "MAVEN_HOME=C:\Workspace\apache-maven-3.9.11-bin\apache-maven-3.9.11" && ^
      set "PATH=%MAVEN_HOME%\bin;%PATH%" && ^
      mvn -version
    displayName: "Verificar Maven"

  # 4️⃣ Publicar resultados JUnit
  - task: PublishTestResults@2
    displayName: "Publicar resultados de pruebas"
    inputs:
      testResultsFiles: '**/surefire-reports/*.xml'
      testRunTitle: 'Resultados Selenium Screenplay'

  # 5️⃣ Publicar reportes HTML de Serenity/Cucumber
  - task: PublishBuildArtifacts@1
    displayName: "Publicar reportes HTML"
    inputs:
      PathtoPublish: 'target/site'
      ArtifactName: 'Reports'
      publishLocation: 'Container'

  # 6️⃣ (Opcional) Publicar reportes de Cucumber
  - task: PublishBuildArtifacts@1
    displayName: "Publicar reportes Cucumber"
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: 'target/cucumber-reports'
      ArtifactName: 'CucumberReports'
      publishLocation: 'Container'
